<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\MateTray.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Product>Mate</Product>
    <Company>LD Desktop</Company>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\MateTray.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.3.0" />
  </ItemGroup>
</Project>
