<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\MateTray.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Product>Mate</Product>
    <Company>LD Desktop</Company>
    <RepositoryUrl>https://github.com/nobard/LD.Desktop.Mate</RepositoryUrl>
    <StartupObject>Mate.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\MateTray.ico" />
    <Resource Include="Assets\MateTrayUpdate.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.3.0" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>
</Project>
